// @flow
export const INIT_FIREBASE : 'FIREBASE/INIT_FIREBASE_REQUEST' = 'FIREBASE/INIT_FIREBASE_REQUEST'
export const INIT_FIREBASE_PENDING : 'FIREBASE/INIT_FIREBASE_PENDING' = 'FIREBASE/INIT_FIREBASE_PENDING'
export const INIT_FIREBASE_SUCCESS : 'FIREBASE/INIT_FIREBASE_SUCCESS' = 'FIREBASE/INIT_FIREBASE_SUCCESS'
export const INIT_FIREBASE_FAILURE : 'FIREBASE/INIT_FIREBASE_FAILURE' = 'FIREBASE/INIT_FIREBASE_FAILURE'
export const SET_USER : 'FIREBASE/SET_USER' = 'FIREBASE/SET_USER'

export type ActionTypes =
  |typeof INIT_FIREBASE
  |typeof INIT_FIREBASE_PENDING
  |typeof INIT_FIREBASE_SUCCESS
  |typeof INIT_FIREBASE_FAILURE
  |typeof SET_USER