// @flow
export const LOGIN : 'ONBOARDING/LOGIN' = 'ONBOARDING/LOGIN'
export const REGISTER : 'ONBOARDING/REGISTER' = 'ONBOARDING/REGISTER'
export const LOGOUT : 'ONBOARDING/LOGOUT' = 'ONBOARDING/LOGOUT'
export const ONBOARDING_PENDING : 'ONBOARDING/LOGIN_PENDING' = 'ONBOARDING/LOGIN_PENDING'
export const ONBOARDING_SUCCESS : 'ONBOARDING/LOGIN_SUCCESS' = 'ONBOARDING/LOGIN_SUCCESS'
export const ONBOARDING_FAILURE : 'ONBOARDING/LOGIN_FAILURE' = 'ONBOARDING/LOGIN_FAILURE'

export type ActionTypes =
  |typeof LOGIN|typeof REGISTER|typeof LOGOUT|typeof ONBOARDING_PENDING
  |typeof ONBOARDING_SUCCESS|typeof ONBOARDING_FAILURE